baseurl = "http://pcf-hugo-prod-workshop.cfapps.io/"
languageCode = "en-us"
title = "Cloud Foundry Workshop"



#theme="hyde-y"
theme="material-design"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "rjain15" # optional
copyright = "Â© Copyright 2016 Pivotal Software, Inc. All Rights Reserved. Sitemap"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "Pivotal"
    topline = "Do the right thing"
    footline = "code with <i class='fa fa-heart'></i>"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"

    description = "Pivotal Cloud Foundry" # optional
    twitter = "pivotal" # optional
    customer = "detroit"
    # headerCover = "images/headerCover.png" # optional
    # footerCover = "images/footerCover.png" # optional
    googleAnalyticsUserID = "UA-75133856-1" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
